In [1]:
import numpy as np
import pandas as pd
import datetime
from pylab import rcParams
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import mean_squared_error
from tqdm import tqdm_notebook
from sklearn.preprocessing import StandardScaler
from tensorflow import set_random_seed
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM
from keras.utils import plot_model
import math
from datetime import date

/anaconda3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
Using TensorFlow backend.

In [2]:
df_1 = pd.read_csv("GOOG.csv")

In [3]:
df_1

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-05-29,1127.520020,1129.099976,1108.219971,1116.459961,1116.459961,1538200
1,2019-05-30,1115.540039,1123.130005,1112.119995,1117.949951,1117.949951,951900
2,2019-05-31,1101.290039,1109.599976,1100.180054,1103.630005,1103.630005,1507800
3,2019-06-03,1065.500000,1065.500000,1025.000000,1036.229980,1036.229980,5130600
4,2019-06-04,1042.900024,1056.050049,1033.689941,1053.050049,1053.050049,2833500
5,2019-06-05,1051.540039,1053.550049,1030.489990,1042.219971,1042.219971,2168400
6,2019-06-06,1044.989990,1047.489990,1033.699951,1044.339966,1044.339966,1703200
7,2019-06-07,1050.630005,1070.920044,1048.400024,1066.040039,1066.040039,1802400
8,2019-06-10,1072.979980,1092.660034,1072.322021,1080.380005,1080.380005,1464200
9,2019-06-11,1093.979980,1101.989990,1077.603027,1078.719971,1078.719971,1436700
10,2019-06-12,1078.000000,1080.930054,1067.540039,1077.030029,1077.030029,1061000
11,2019-06-13,1083.640015,1094.170044,1080.150024,1088.770020,1088.770020,1057700
12,2019-06-14,1086.420044,1092.689941,1080.171997,1085.349976,1085.349976,1111500
13,2019-06-17,1086.280029,1099.180054,1086.280029,1092.500000,1092.500000,941600
14,2019-06-18,1109.689941,1116.390015,1098.989990,1103.599976,1103.599976,1386700
15,2019-06-19,1105.599976,1107.000000,1093.479980,1102.329956,1102.329956,1338800
16,2019-06-20,1119.989990,1120.119995,1104.739990,1111.420044,1111.420044,1262000
17,2019-06-21,1109.239990,1124.109985,1108.079956,1121.880005,1121.880005,1947600
18,2019-06-24,1119.609985,1122.000000,1111.010010,1115.520020,1115.520020,1395600
19,2019-06-25,1112.660034,1114.349976,1083.800049,1086.349976,1086.349976,1546900
20,2019-06-26,1086.500000,1092.969971,1072.239990,1079.800049,1079.800049,1810900
21,2019-06-27,1084.000000,1087.099976,1075.290039,1076.010010,1076.010010,1004300
22,2019-06-28,1076.390015,1081.000000,1073.369995,1080.910034,1080.910034,1693200
23,2019-07-01,1098.000000,1107.579956,1093.703003,1097.949951,1097.949951,1436300
24,2019-07-02,1102.239990,1111.770020,1098.170044,1111.250000,1111.250000,991600
25,2019-07-03,1117.410034,1126.760010,1113.859985,1121.579956,1121.579956,767000
26,2019-07-05,1117.800049,1132.880005,1116.140015,1131.589966,1131.589966,1264300
27,2019-07-08,1125.170044,1125.979980,1111.209961,1116.349976,1116.349976,1236400
28,2019-07-09,1111.800049,1128.025024,1107.170044,1124.829956,1124.829956,1330400
29,2019-07-10,1131.219971,1142.050049,1130.969971,1140.479980,1140.479980,1209500
...,...,...,...,...,...,...,...
70,2019-09-06,1208.130005,1212.015015,1202.521973,1204.930054,1204.930054,1072100
71,2019-09-09,1204.000000,1220.000000,1192.619995,1204.410034,1204.410034,1471900
72,2019-09-10,1195.150024,1210.000000,1194.579956,1206.000000,1206.000000,1260100
73,2019-09-11,1203.410034,1222.599976,1202.199951,1220.170044,1220.170044,1307000
74,2019-09-12,1224.300049,1241.859985,1223.020020,1234.250000,1234.250000,1725900
75,2019-09-13,1231.349976,1240.880005,1227.010010,1239.560059,1239.560059,1301400
76,2019-09-16,1229.520020,1239.560059,1225.609985,1231.300049,1231.300049,1053300
77,2019-09-17,1230.400024,1235.000000,1223.689941,1229.150024,1229.150024,955100
78,2019-09-18,1227.510010,1235.609985,1216.530029,1232.410034,1232.410034,1135100
79,2019-09-19,1232.060059,1244.439941,1232.020020,1238.709961,1238.709961,996000
80,2019-09-20,1233.119995,1243.319946,1223.079956,1229.930054,1229.930054,2270000
81,2019-09-23,1226.000000,1239.089966,1224.170044,1234.030029,1234.030029,1062400
82,2019-09-24,1240.000000,1246.739990,1210.680054,1218.760010,1218.760010,1583200
83,2019-09-25,1215.819946,1248.300049,1210.089966,1246.520020,1246.520020,1453000
84,2019-09-26,1241.959961,1245.000000,1232.267944,1241.390015,1241.390015,1538000
85,2019-09-27,1243.010010,1244.020020,1214.449951,1225.089966,1225.089966,1353900
86,2019-09-30,1220.969971,1226.000000,1212.300049,1219.000000,1219.000000,1404100
87,2019-10-01,1219.000000,1231.229980,1203.579956,1205.099976,1205.099976,1273500
88,2019-10-02,1196.979980,1196.979980,1171.290039,1176.630005,1176.630005,1615100
89,2019-10-03,1180.000000,1189.060059,1162.430054,1187.829956,1187.829956,1621200
90,2019-10-04,1191.890015,1211.439941,1189.170044,1209.000000,1209.000000,1162400
91,2019-10-07,1204.400024,1218.203979,1203.750000,1207.680054,1207.680054,842900
92,2019-10-08,1197.589966,1206.079956,1189.010010,1189.130005,1189.130005,1039300
93,2019-10-09,1199.349976,1208.349976,1197.630005,1202.310059,1202.310059,867700
94,2019-10-10,1198.579956,1215.000000,1197.339966,1208.670044,1208.670044,846600
95,2019-10-11,1222.209961,1228.390015,1213.739990,1215.449951,1215.449951,1272700
96,2019-10-14,1212.339966,1226.329956,1211.760010,1217.140015,1217.140015,867500
97,2019-10-15,1220.400024,1247.329956,1220.400024,1243.010010,1243.010010,1381700
98,2019-10-16,1241.170044,1254.739990,1238.449951,1243.640015,1243.640015,1094600
99,2019-10-17,1250.930054,1263.324951,1249.939941,1253.069946,1253.069946,952400

In [4]:
df_2 = pd.read_csv("df_RNN.csv")

In [5]:
df_2

    Unnamed: 0        date     open     high      low  adj_close**  sentiments
0           99  2019-05-29  1127.52  1129.10  1108.22      1116.46    0.199160
1           98  2019-05-30  1115.54  1123.13  1112.12      1117.95    0.024045
2           97  2019-05-31  1101.29  1109.60  1100.18      1103.63    0.199324
3           96  2019-06-03  1065.50  1065.50  1025.00      1036.23    0.140989
4           95  2019-06-04  1042.90  1056.05  1033.69      1053.05    0.139237
5           94  2019-06-05  1051.54  1053.55  1030.49      1042.22    0.128009
6           93  2019-06-06  1044.99  1047.49  1033.70      1044.34   -0.121932
7           92  2019-06-07  1050.63  1070.92  1048.40      1066.04    0.002834
8           91  2019-06-10  1072.98  1092.66  1072.32      1080.38   -0.116249
9           90  2019-06-11  1093.98  1101.99  1077.60      1078.72    0.173841
10          89  2019-06-12  1078.00  1080.93  1067.54      1077.03    0.158118
11          88  2019-06-13  1083.64  1094.17  1080.15      1088.77    0.145342
12          87  2019-06-14  1086.42  1092.69  1080.17      1085.35    0.193001
13          86  2019-06-17  1086.28  1099.18  1086.28      1092.50    0.167590
14          85  2019-06-18  1109.69  1116.39  1098.99      1103.60    0.181690
15          84  2019-06-19  1105.60  1107.00  1093.48      1102.33    0.195269
16          83  2019-06-20  1119.99  1120.12  1104.74      1111.42    0.163177
17          82  2019-06-21  1109.24  1124.11  1108.08      1121.88    0.189569
18          81  2019-06-24  1119.61  1122.00  1111.01      1115.52    0.029260
19          80  2019-06-25  1112.66  1114.35  1083.80      1086.35   -0.007065
20          79  2019-06-26  1086.50  1092.97  1072.24      1079.80    0.183344
21          78  2019-06-27  1084.00  1087.10  1075.29      1076.01    0.033702
22          77  2019-06-28  1076.39  1081.00  1073.37      1080.91    0.180193
23          76  2019-07-01  1098.00  1107.58  1093.70      1097.95    0.201865
24          75  2019-07-02  1102.24  1111.77  1098.17      1111.25    0.195238
25          74  2019-07-03  1117.41  1126.76  1113.86      1121.58    0.171817
26          73  2019-07-05  1117.80  1132.88  1116.14      1131.59    0.034289
27          72  2019-07-08  1125.17  1125.98  1111.21      1116.35   -0.096034
28          71  2019-07-09  1111.80  1128.03  1107.17      1124.83    0.150651
29          70  2019-07-10  1131.22  1142.05  1130.97      1140.48    0.193030
..         ...         ...      ...      ...      ...          ...         ...
70          29  2019-09-06  1208.13  1212.02  1202.52      1204.93    0.074718
71          28  2019-09-09  1204.00  1220.00  1192.62      1204.41    0.174363
72          27  2019-09-10  1195.15  1210.00  1194.58      1206.00    0.051360
73          26  2019-09-11  1203.41  1222.60  1202.20      1220.17   -0.025785
74          25  2019-09-12  1224.30  1241.86  1223.02      1234.25    0.025399
75          24  2019-09-13  1231.35  1240.88  1227.01      1239.56    0.099602
76          23  2019-09-16  1229.52  1239.56  1225.61      1231.30    0.206555
77          22  2019-09-17  1230.40  1235.00  1223.69      1229.15   -0.067362
78          21  2019-09-18  1227.51  1235.61  1216.53      1232.41    0.182087
79          20  2019-09-19  1232.06  1244.44  1232.02      1238.71    0.044522
80          19  2019-09-20  1233.12  1243.32  1223.08      1229.93    0.130114
81          18  2019-09-23  1226.00  1239.09  1224.17      1234.03    0.104840
82          17  2019-09-24  1240.00  1246.74  1210.68      1218.76    0.193752
83          16  2019-09-25  1215.82  1248.30  1210.09      1246.52    0.143535
84          15  2019-09-26  1241.96  1245.00  1232.27      1241.39    0.081002
85          14  2019-09-27  1243.01  1244.02  1214.45      1225.09    0.204399
86          13  2019-09-30  1220.97  1226.00  1212.30      1219.00    0.206465
87          12  2019-10-01  1219.00  1231.23  1203.58      1205.10    0.150039
88          11  2019-10-02  1196.98  1196.98  1171.29      1176.63   -0.018772
89          10  2019-10-03  1180.00  1189.06  1162.43      1187.83    0.193018
90           9  2019-10-04  1191.89  1211.44  1189.17      1209.00    0.139398
91           8  2019-10-07  1204.40  1218.20  1203.75      1207.68    0.188636
92           7  2019-10-08  1197.59  1206.08  1189.01      1189.13    0.162102
93           6  2019-10-09  1199.35  1208.35  1197.63      1202.31    0.193995
94           5  2019-10-10  1198.58  1215.00  1197.34      1208.67    0.198575
95           4  2019-10-11  1222.21  1228.39  1213.74      1215.45    0.148308
96           3  2019-10-14  1212.34  1226.33  1211.76      1217.14   -0.062707
97           2  2019-10-15  1220.40  1247.33  1220.40      1243.01    0.132530
98           1  2019-10-16  1241.17  1254.74  1238.45      1243.64    0.187204
99           0  2019-10-17  1250.93  1263.32  1249.94      1253.07    0.052831

[100 rows x 7 columns]

In [8]:
df = df_1.join(df_2['sentiments'])

In [9]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,sentiments
0,2019-05-29,1127.520020,1129.099976,1108.219971,1116.459961,1116.459961,1538200,0.199160
1,2019-05-30,1115.540039,1123.130005,1112.119995,1117.949951,1117.949951,951900,0.024045
2,2019-05-31,1101.290039,1109.599976,1100.180054,1103.630005,1103.630005,1507800,0.199324
3,2019-06-03,1065.500000,1065.500000,1025.000000,1036.229980,1036.229980,5130600,0.140989
4,2019-06-04,1042.900024,1056.050049,1033.689941,1053.050049,1053.050049,2833500,0.139237

In [10]:
test_size = 0.2
N = 9
lstm_units = 128
dropout_prob = 1
optimizer = 'nadam'
epochs = 50
batch_size = 8

In [9]:
df_1.loc[:, 'Date'] = pd.to_datetime(df_1['Date'],format='%Y-%m-%d')

In [10]:
type(df_1['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp